# AI-driven SIEM Hybrid Log Anomaly Detection Configuration

# Data paths configuration
data_paths:
  input_dir: "data/logs/raw/"
  output_dir: "data/logs/processed/"
  reports_dir: "reports/logAnomalyDetection/"

# Parsing configuration (Brain algorithm)
parsing:
  algorithm: "Brain"
  dataset: "Linux"
  log_format: '<Month> <Date> <Time> <Level> <Component>(\[<PID>\])?: <Content>'
  parameters:
    threshold: 4
    depth: 4
    st: 0.4
    maxChild: 100
    mergeThreshold: 0.9
    regex: 
      - '(\d+\.){3}\d+'
      - '\d{2}:\d{2}:\d{2}'
      - 'J([a-z]{2})'
    delimeter: [""]
  
  # Validation settings
  validation:
    required_columns: ["EventTemplate", "EventId"]
    optional_columns: ["Content", "Level", "Component", "Date", "Time"]
    validate_output: true

# Hybrid detection configuration
detection:
  # Model and artifact paths
  model_path: "src/logAnomalyDetection/LSTM_AE/"
  output_path: "reports/logAnomalyDetection/"
  
  # Hybrid processing parameters
  seq_len: 8
  stride: 8
  batch_size: 32
  
  # Processing modes: sequential, single, hybrid, both
  default_processing_mode: "both"
  available_modes: ["sequential", "single", "hybrid", "both"]
  
  # Model ensemble configuration
  ensemble:
    num_models: 3
    enable_single_log: true
    model_configs:
      - hidden_dim: 16
        dropout: 0.3
      - hidden_dim: 24
        dropout: 0.4
      - hidden_dim: 32
        dropout: 0.2
  
  # Anomaly detection thresholds
  thresholds:
    anomaly_percentile: 95
    static_threshold_percentile: 95
    adaptive_threshold: true
  
  # Severity classification
  severity:
    percentiles: [85, 95, 99]
    labels: ["Low", "Medium", "High", "Critical"]
    confidence_calculation: true
  
  # Feature engineering
  preprocessing:
    max_tfidf_features: 50
    max_categorical_features: 50
    content_feature_extraction: true
    remove_temporal_features: true
    handle_high_cardinality: true
    cardinality_threshold: 1000
  
  # Rule-based classification
  classification:
    enable_rule_based: true
    confidence_threshold: 0.7
    filter_normal_types: true
    classification_rules:
      memory_error:
        - '\b(out of memory|oom|page allocation failure|dma timeout)\b'
        - '\b(malloc failed|memory leak|segfault|kernel panic)\b'
        - '\b(swap.*full|virtual memory|memory pressure)\b'
      authentication_error:
        - '\b(authentication failure|invalid username|login failed)\b'
        - '\b(kerberos.*failed|pam_unix.*failed|ssh.*failed)\b'
        - '\b(password.*incorrect|access denied|unauthorized)\b'
      filesystem_error:
        - '\b(no such file|permission denied|disk full|quota exceeded)\b'
        - '\b(failed command|status timeout|drive not ready|io error)\b'
        - '\b(filesystem.*corrupt|bad sector|read.*error)\b'
      network_error:
        - '\b(connection timed out|connection refused|peer died)\b'
        - '\b(network unreachable|socket error|host.*down)\b'
        - '\b(dns.*failed|routing.*error|packet.*lost)\b'
      permission_error:
        - '\b(permission denied|operation not supported|access forbidden)\b'
        - '\b(selinux.*denied|capability.*denied|privilege.*error)\b'
        - '\b(sudo.*failed|su.*failed|root.*access)\b'
      system_critical:
        - '\b(critical|fatal|panic|emergency|alert)\b'
        - '\b(system.*halt|kernel.*oops|hardware.*error)\b'
        - '\b(temperature.*critical|power.*failure)\b'

# Pipeline execution options
execution:
  # Processing modes
  enable_hybrid_processing: true
  enable_parallel_modes: true
  
  # Memory and performance
  enable_gpu: false
  max_memory_usage: "4GB"
  parallel_processing: false
  device: "cpu"
  
  # Error handling
  continue_on_errors: true
  max_retries: 3
  early_stopping_patience: 5
  
  # Validation
  validate_inputs: true
  validate_outputs: true
  validate_preprocessing: true

# Output configuration
output:
  # Hybrid-specific outputs
  save_mode_comparison: true
  save_individual_modes: true
  generate_hybrid_analysis: true
  
  # File generation
  save_detailed_results: true
  save_single_log_anomalies: true
  save_sequential_anomalies: true
  save_hybrid_anomalies: true
  save_raw_scores: false
  
  # Report generation
  generate_summary_report: true
  generate_detailed_report: true
  generate_mode_comparison_report: true
  
  # Display settings
  max_display_results: 10
  max_display_sequences: 5
  show_log_content: true
  truncate_content_length: 100
  
  # Format options
  output_format: "json"
  compress_outputs: false
  ensure_json_serializable: true
  
  # Retention
  keep_intermediate_files: false
  max_output_files: 100

# Logging and monitoring
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: false
  log_file: "logs/pipeline.log"
  enable_progress_bars: true
  
# Alerting thresholds (for future SIEM integration)
alerting:
  # Severity-based thresholds
  critical_anomaly_threshold: 1
  high_anomaly_threshold: 5
  anomaly_rate_threshold: 10.0
  
  # Mode-specific thresholds
  sequential_alert_threshold: 3
  single_log_alert_threshold: 10
  hybrid_alert_threshold: 5
  
  # Alert types
  enable_email_alerts: false
  enable_webhook_alerts: false
  enable_syslog_alerts: false

# Performance monitoring
monitoring:
  track_processing_time: true
  track_memory_usage: true
  track_model_performance: true
  track_mode_performance: true
  
  # Metrics collection
  collect_pipeline_metrics: true
  collect_hybrid_metrics: true
  metrics_retention_days: 30

# Advanced hybrid features
hybrid_features:
  # Processing optimization
  consistency_regularization: true
  consistency_weight: 0.1
  fusion_weights:
    sequential: 0.6
    single_log: 0.4
  
  # Ensemble weighting
  dynamic_ensemble_weights: true
  weight_update_strategy: "performance_based"
  
  # Attention mechanisms
  enable_attention: true
  attention_heads: 4
  attention_dropout: 0.4
  
  # Model architecture
  bidirectional_lstm: true
  lstm_layers: 2
  batch_normalization: true
  gradient_clipping: 1.0

# Integration settings
integration:
  # SIEM compatibility
  siem_format_output: true
  enable_real_time_processing: false
  buffer_size: 8
  
  # API endpoints (for future use)
  enable_api_endpoints: true
  api_port: 8080
  
  # Database integration (for future use)
  enable_database_logging: false
  database_connection: null

# Experimental features
experimental:
  # Advanced preprocessing
  enable_advanced_feature_extraction: true
  enable_semantic_analysis: false
  
  # Model improvements
  enable_transfer_learning: false
  enable_online_learning: false
  
  # Visualization
  enable_attention_visualization: false
  enable_anomaly_visualization: false

# Express Backend Integration (matches your server.js)
express_backend:
  enabled: true  # Set to true when you want to enable
  base_url: "http://localhost:5000"  # Your server port
  timeout: 30
  retry_attempts: 3
